Add .config and make the kernel build on gcc (Ubuntu 4.9.2-0ubuntu1~14.04)
This is the gcc I use in my Ubuntu 14.04 host.
Also define EXTRAVERSION to -LIS4.

NOTE 1:
I disabled CONFIG_STAGING.
Since the in-tree LIS modules are in drivers/staging/hv/, this actually
disabled the modules.
We did this intentionally because we know the in-tree LIS modues of 2.6.37
don't work very well.

NOTE 2: I disabled the 2 options
CONFIG_XEN
CONFIG_IGBVF
due to the known build issues:
https://bugzilla.kernel.org/show_bug.cgi?id=31062
https://github.com/AshishPrasad/BTP/blob/master/2.6.36%20Kernel%20Compilation%20Problems

NOTE 3:
I also disabled video4linxu document build due to
http://www.howopensource.com/2011/08/how-to-install-compile-linux-kernel-3-0-in-fedora-15-and-14/

HOSTCC Documentation/video4linux/v4lgrab
Documentation/video4linux/v4lgrab.c:34:28: fatal error: linux/videodev.h: No
such file or directory

Signed-off-by: Dexuan Cui <decui@microsoft.com>